### ISSUE TITLE
Fails to retrieve image if separate user/pass defined

### ISSUE THREAD

**Issue by infernix** [jeradM/pyxeoma#1]
Fetching the image does not seem to work if the image and video files have an additional (different) username and password configured. This is the case when they are allowed to be accessed directly without having a login into xeomas web interface itself. 

I think that should either be added as a config option (e.g. admin credentials + optional viewing credentials), or the generated username needs to be parsed from the web api homepage when logged in as admin.

For example, after logging in, the camera video feed image url looks like:
`image-url="http://localhost:10091/video.mjpg?user=xxXXXXXXXXXXX%3D%3D&resolution=320x240&fps=1&oneframe=1"`

that user= variable can be passed into `GET /image.jpg?user=` and then it works fine.

If parsing is problematic, the configured viewing credentials can be passed in as `GET /image.jpg?login=foo&password=bar`

**Comment by jeradM** [comment]
Thanks for finding this and for the detailed explanation. This should be a pretty easy fix, but I will have to do some testing after work to determine the best solution. The `user` parameter is just a base64 then URL encoded string of `username:password` for the "viewer" user so it should be straightforward to parse it during setup and also allow it to be overridden on a global and/or per-camera basis in Home Assistant.

**Comment by jeradM** [comment]
I just pushed some changes that should fix this. I still need to clean up the changes to the hass component, but I will try to get those submitted in time to make it into the next release
