### ISSUE TITLE
Is unable to find cameras anymore using async_get_image_names

### ISSUE THREAD

**Issue by bfayers** [jeradM/pyxeoma#3]
No longer seems to work after a xeoma update to the WebUI. I think its a problem with the regex used.

I use this inside of home-assistant and the problem is that it seems to only add cameras if they pass the checks introduced with `async_get_image_names` and ofcourse this failing means no cameras are added.

One solution i suppose would be a config option to just add cameras anyway even if they dont pass `async_get_image_names` 

anyway hopefully you can look into this. thanks.

**Comment by trunet** [comment]
this should fix https://github.com/home-assistant/home-assistant/issues/19306
