### ISSUE TITLE
Is there anyone maintaining this? Need help?

### ISSUE THREAD

**Issue by trunet** [jeradM/pyxeoma#5]
Let me know, I can take care of it. It's important to have this working to keep homeassistant happy.

**Comment by jeradM** [comment]
Hey sorry, I haven't had much time for this lately and I don't use Xeoma anymore so I don't have any way to test the changes. I added you to the repo

**Comment by jeradM** [comment]
Do you have a pypi account so I can add you as a collab there for the pip package?

**Comment by trunet** [comment]
Hello. Sure... it’s trunet

https://pypi.org/user/trunet/

**Comment by jeradM** [comment]
Cool, just added you there too

**Comment by trunet** [comment]
Thanks man. I will do my best!

**Comment by trunet** [comment]
I will send the new version tomorrow. Do you gave the correct permissions to upload a new version on pypi?

**Comment by jeradM** [comment]
Yeah you are a maintainer on the package now
