### ISSUE TITLE
Tag 1.4.1

### ISSUE THREAD

**Issue by fabaff** [jeradM/pyxeoma#8]
On PyPI 1.4.1 is available but the latest release on GitHub is [1.4.0](https://github.com/jeradM/pyxeoma/releases/latest).

Could you please tag the released? This allows one to use the GitHub source tarballs.

Thanks

**Comment by jeradM** [comment]
Thanks Fabian. Tagged 1.4.1 then merged your PRs and tagged 1.4.2
